document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('birth-form');
  const reportDiv = document.getElementById('report-output');

  form.addEventListener('submit', (e) => {
    e.preventDefault();

    const name = document.getElementById('name').value.trim();
    const birthdate = document.getElementById('birthdate').value;
    const birthtime = document.getElementById('birthtime').value;
    const birthplace = document.getElementById('birthplace').value.trim();

    if (!name || !birthdate || !birthtime || !birthplace) {
      reportDiv.innerHTML = '<p class="error">Please fill in all fields.</p>';
      return;
    }

    // ✨ Placeholder logic – real KP/NASA data will be added in next phase
    const reportHTML = `
      <h3>🌟 Personalized Birth Report for ${name}</h3>
      <p><strong>Date:</strong> ${birthdate}</p>
      <p><strong>Time:</strong> ${birthtime}</p>
      <p><strong>Place:</strong> ${birthplace}</p>
      <hr>
      <p>This is a sample astrological birth report generated by Buddhi AI. Future phases will include Sub-Lord, Star Lord, Nakshatra, and planetary positions.</p>
    `;

    reportDiv.innerHTML = reportHTML;
  });
});