name: Deploy Static Site

on:
  push:
    branches:
      - main  # ඔබේ main branch එකට අනුව මෙය වෙනස් කරන්න

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # ඔබේ HTML files තියෙන root folder එක

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4